# Generated by Django 4.2.1 on 2023-05-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pcimage',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
